language: php
php:
  # X.Y versions are aliases for recent X.Y.Z releases pre-installed on the build images
  - '5.6.0'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
before_install: 
  - "composer --no-plugins --no-scripts install"
  - "composer --no-plugins --no-scripts dump-autoload -o"
script: 
  - "vendor/bin/phpunit --configuration ./phpunit.xml --teamcity"