language: php
php:
    # X.Y versions are aliases for recent X.Y.Z releases pre-installed on the build images
    - '5.6.0'
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'
before_install: "composer install"
script: "vendor/bin/phpunit --no-configuration ./tests --teamcity"